config/routes.rb
FantasyDraft::Application.routes.draw do

  resources :players do
    member do
      post 'pick'
      post 'unpick'
    end
  end
  resources :positions
  resources :sources
  resources :rankings

  get 'fetch' => 'players#fetch'
  get 'clear' => 'players#clear'

  root 'welcome#index'

  

end

app/models/player.rb
require 'open-uri'

class Player < ActiveRecord::Base
  include Clear
  belongs_to :position

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :position, presence: true
  validates :team, presence: true

  after_validation :remove_suffix

  def self.populate
    Source.all.each do |source|
      add_players source.fetch
      add_players(source.fetch('http://fantasy.nfl.com/research/rankings?leagueId=0&statType=draftStats&offset=101')) if source.nfl?
    end

    Ranking.populate
    Player.all
  end

  def self.clear_picks!
    Player.all.each do |p|
      next if !p.picked?
      p.unpick!
    end
  end

  def pick!
    self.picked = true
    self.save
  end

  def unpick!
    self.picked = false
    self.save
  end

  def picked?
    self.picked || false
  end

  def picked_recently?
    (self.picked && (self.updated_at < (Time.now - 60.seconds))) || false
  end

  private

  def self.add_players players_arry
    players_arry.each do |player|
      next if player.blank?

      found_player = Player.find_player(player)
      if found_player.empty?
        Player.create!(first_name: player[:first_name],
                       last_name:  player[:last_name],
                       team:       player[:team],
                       position:   player[:position])
      end
    end
  end

  def self.parse_player player_string
    player_hash = {}
    player_arry = player_string.gsub(/,/,'').split(' ')[1..2]

    player_hash[:first_name] = player_arry.first.strip
    player_hash[:last_name]  = player_arry.last.strip
    player_hash
  end

  def self.find_player(player_hash)
    sanitized_last_name = Player.remove_suffix(player_hash[:last_name])
    Player.where('last_name' => sanitized_last_name, 'team' => player_hash[:team], 'position' => player_hash[:position]) ||
      Player.where('first_name' => player_hash[:first_name], 'last_name' => sanitized_last_name, 'team' => player_hash[:team])
  end

  def self.remove_suffix last_name
    last_name = last_name.gsub(/jr[.]?$/i, '').strip
    last_name = last_name.gsub(/V$/i, '').strip
    last_name = last_name.gsub(/II$/i, '').strip
    last_name = last_name.gsub(/III$/i, '').strip
    last_name
  end

  def remove_suffix
    self.last_name = Player.remove_suffix(self.last_name)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  def fetch
    @ret = Player.populate
    redirect_to rankings_url
  end

  def clear
    Player.clear_picks!
    redirect_to rankings_url
  end

  # PATCH/PUT /players/pick/1
  # PATCH/PUT /players/pick/1.json
  def pick
    @player = Player.find(params[:id])
    @player.pick!
    redirect_to rankings_url
  end

  def unpick
    @player = Player.find(params[:id])
    @player.unpick!
    redirect_to rankings_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:first_name, :last_name, :position_id, :team)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :team %><br>
    <%= f.text_field :team %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/fetch.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fetch!</strong>
</p>

<p><%= @ret %></p>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Position</th>
      <th>Team</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.first_name %></td>
        <td><%= player.last_name %></td>
        <td><%= player.position.abbrev %></td>
        <td><%= player.team %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @player.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @player.last_name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @player.position.name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @player.team %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>